services:
  backend:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_IDENTIFIER: ${AUTH0_IDENTIFIER}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SECRET_NAME: ${DB_SECRET_NAME}
      ECS_CONTAINER_METADATA_URI: ${ECS_CONTAINER_METADATA_URI}
    env_file:
      - ./core/.env
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    depends_on:
      - nginx