AWSTemplateFormatVersion: "2010-09-09"
Description: >
  API Gateway to Private HTTP Endpoint via VPC Link.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC
    Default: "vpc-07d8bd9c2741a8aa1"
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-09fc8618a1ff7aa7d,subnet-01644fa89f0d7ec1a"
  # ECSFargateCluster: 
  #   Type : AWS::ECS::Cluster
  #   Description: ARN to the ECS cluster
  TaskName:
    Type: String
    Description: The name of the service task
    Default: "cvh-api-2"
  TaskEnvFile:
    Type: String
    Description: The ARN for the environment file in S3 
    Default: "arn:aws:s3:::cvh-api-env/cvh-api.env"
  ImageURI:
    Type: String
    Description: The URI of the image to deploy
    Default: "605134458779.dkr.ecr.us-east-1.amazonaws.com/cvh-api:latest"
  DbInfo:
    Type: String
    Description: The ARN of the database secret
    NoEcho: true
  DbSG:
    Type: String
    Description: The security group ID attached to the database
    Default: "sg-081c800846aca6d1c"

Resources:
  # Security Group for the Load Balancer
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "LoadBalancer Security Group"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow from anyone on port 80
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      Tags: 
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSService'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'cvh'
      VpcId: !Ref VpcId
      

  # Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !GetAtt LoadBalancerSG.GroupId
      Subnets: !Ref PrivateSubnetIds
      Tags: 
        - Key: project
          Value: 'cvh'
      Type: application


  # ECS Security Group
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ECS Security Group"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags: 
        - Key: project
          Value: 'cvh'
      VpcId: !Ref VpcId

  # Access to RDS from ECS Security Group
  RDSOutboundRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId: !Ref DbSG
      GroupId: !GetAtt ECSSecurityGroup.GroupId
  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt ECSSecurityGroup.GroupId
      GroupId: !Ref DbSG

  # Target Group for ECS Service
  LoadBalancerListenerTargetGroupECS:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /health     
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: project
          Value: 'cvh'
        - Key: component
          Value: 'cvh-api'
      TargetType: ip
      VpcId: !Ref VpcId

  # Load Balancer Listener
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref LoadBalancerListenerTargetGroupECS
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  # ECS Cluster
  ECSFargateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      Tags: 
        - Key: project
          Value: 'cvh'

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSFargateCluster
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 50
      DesiredCount: 2
      EnableECSManagedTags: true
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !Ref TaskName
          ContainerPort: 8000
          TargetGroupArn: !Ref LoadBalancerListenerTargetGroupECS
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !GetAtt ECSSecurityGroup.GroupId
          Subnets: !Ref PrivateSubnetIds
      Tags: 
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSService'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'cvh'
      TaskDefinition: !Ref ECSServiceTaskDefinition
    DependsOn:
      - LoadBalancerListenerTargetGroupECS
      - LoadBalancerListener

  # ECS Task Definition
  ECSServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Ref TaskName
          Image: !Ref ImageURI 
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          EnvironmentFiles: 
            - Type: s3
              Value: !Ref TaskEnvFile
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub
                - "/ecs/${Task}-task-definition"
                - Task: !Ref TaskName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Cpu: '1024'
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      Family: !Sub
        - "${Task}-task-definition"
        - Task: !Ref TaskName
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Tags:
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSTaskDef'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'cvh'
        - Key: component
          Value: 'cvh-api'
      TaskRoleArn: !Ref TaskContainerRole
    DependsOn:
      - TaskContainerRole
      
  TaskContainerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cvh-api-container
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket                  
                Resource: [
                  !Ref TaskEnvFile,
                  "arn:aws:s3:::cvh-seed-data",
                  "arn:aws:s3:::cvh-seed-data/*"
                ]
              - Sid: RdsAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DbInfo
              - Sid: ECR
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"
              - Sid: Logging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: ["arn:aws:logs:*:*:*"]
      Tags:
        - Key: Name
          Value: !Sub
            - '${StackName}:TaskContainerRole'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'cvh'
        - Key: component
          Value: 'cvh-api'

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ecs-service-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: cloudwatch-logs-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"
        - PolicyName: s3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Ref TaskEnvFile
      Tags:
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSExecutionRole'
            - StackName: !Ref AWS::StackName

  # Create the VPC Link configured with the private subnets. Security groups are kept empty here, but can be configured as required.
  VpcLink:
    Type: 'AWS::ApiGatewayV2::VpcLink'
    Properties:
      Name: APIGWVpcLinkToPrivateHTTPEndpoint-2
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds: []
    DependsOn:
      - TaskContainerRole
      - ECSServiceTaskDefinition

  # Create the API Gateway HTTP endpoint
  APIGWHTTPEndpoint:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: serverlessland-pvt-endpoint
      ProtocolType: HTTP
  # Create the API Gateway HTTP_PROXY integration between the created API and the private load balancer via the VPC Link.
  # Ensure that the 'DependsOn' attribute has the VPC Link dependency.
  # This is to ensure that the VPC Link is created successfully before the integration and the API GW routes are created.
  APIGWHTTPEndpointIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref APIGWHTTPEndpoint
      IntegrationType: HTTP_PROXY
      ConnectionId: !Ref VpcLink
      ConnectionType: VPC_LINK
      IntegrationMethod: ANY
      IntegrationUri: !Ref LoadBalancerListener
      PayloadFormatVersion: '1.0'
    DependsOn:
    - VpcLink
    - APIGWHTTPEndpoint
    - LoadBalancerListener
  # API GW route with ANY method
  APIGWRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref APIGWHTTPEndpoint
      RouteKey: 'ANY /{proxy+}'
      Target: !Join 
        - /
        - - integrations
          - !Ref APIGWHTTPEndpointIntegration
    DependsOn:
    - APIGWHTTPEndpointIntegration
  # Set a default stage
  APIStageDefault:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref APIGWHTTPEndpoint
      StageName: $default
      AutoDeploy: true
    DependsOn:
      - APIGWHTTPEndpoint

Outputs:
  # Generated API GW endpoint URL that can be used to access the application running on a private ECS Fargate cluster.
  APIGWEndpoint:
    Description: API Gateway Endpoint
    Value: !GetAtt APIGWHTTPEndpoint.ApiEndpoint
  
  ECSCluster: 
    Description: A reference to the ECS cluster
    Value: !Ref ECSFargateCluster

  ECSClusterTaskDef: 
    Description: The ECS cluster task definition
    Value: !Ref ECSServiceTaskDefinition

  ECSClusterService: 
    Description: The ECS cluster service definition
    Value: !Ref ECSService

  ECSExecutionRole: 
    Description: The ECS execution role
    Value: !Ref ECSExecutionRole

  LoadBalancerDNSName:
    Description: "DNS name of the load balancer"
    Value: !GetAtt LoadBalancer.DNSName
