AWSTemplateFormatVersion: "2010-09-09"
Description: >
  ECS Fargate Cluster and Task Definition
Parameters:
  EcsClusterName:
    Type: String
    Description: The name of the ECS Cluster
    Default: "gosling-dmc-api-no-lb"    
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC
    Default: "vpc-0032aab40699a6b32"
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-0b17025a76b1d74a3,subnet-0d2e5b8795e4569c0,subnet-059c833c815115bb5"
  # PrivateSubnetIds:
  #   Type: List<AWS::EC2::Subnet::Id>
  #   Default: "subnet-09fc8618a1ff7aa7d,subnet-01644fa89f0d7ec1a"
  TaskName:
    Type: String
    Description: The name of the service task
    Default: "gosling-dmc-api-no-lb"
  TaskEnvFile:
    Type: String
    Description: The ARN for the environment file in S3 
    Default: "arn:aws:s3:::gosling-dmc-env/gosling-dmc-env.env"
  ImageURI:
    Type: String
    Description: The URI of the image to deploy
    Default: "765139173785.dkr.ecr.us-east-2.amazonaws.com/gosling/dmc:latest"
  DbInfo:
    Type: String
    Description: The ARN of the database secret in Secrets Manager
    NoEcho: true
  DbSG:
    Type: String
    Description: The security group ID attached to the database
    Default: "sg-064851831f18d03a0"

Resources:
  # Security Group for the Load Balancer
  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "LoadBalancer Security Group"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
          # Description: Allow from anyone on port 80
          # FromPort: 80
          # IpProtocol: tcp
          # ToPort: 80
      Tags: 
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSService'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'gosling-dmc'
      VpcId: !Ref VpcId


  # Load Balancer
  # Internal load balancer
  # LoadBalancer:
  #   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  #   Properties:
  #     Scheme: internal
  #     SecurityGroups:
  #       - !GetAtt LoadBalancerSG.GroupId
  #     Subnets: !Ref PrivateSubnetIds
  #     Tags: 
  #       - Key: project
  #         Value: 'gosling-dmc'
  #     Type: application
  # 
  # External load balancer - as alternate to above internal version
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt LoadBalancerSG.GroupId
      Subnets: !Ref PublicSubnetIds
      Tags: 
        - Key: project
          Value: 'gosling-dmc'
      Type: application


  # ECS Security Group
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ECS Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 8000
          # CidrIp: 0.0.0.0/0
          SourceSecurityGroupId: !Ref 'LoadBalancerSG'
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 80
          # CidrIp: 0.0.0.0/0
          SourceSecurityGroupId: !Ref 'LoadBalancerSG'
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags: 
        - Key: project
          Value: 'gosling-dmc'
      VpcId: !Ref VpcId

  # Access to RDS from ECS Security Group
  RDSOutboundRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId: !Ref DbSG
      GroupId: !GetAtt ECSSecurityGroup.GroupId
  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !GetAtt ECSSecurityGroup.GroupId
      GroupId: !Ref DbSG

  # Target Group for ECS Service
  LoadBalancerListenerTargetGroupECS:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /health     
      Port: 8000
      Protocol: HTTP
      Tags:
        - Key: project
          Value: 'gosling-dmc'
        - Key: component
          Value: 'gosling-dmc-api'
      TargetType: ip
      VpcId: !Ref VpcId
 

  # Load Balancer Listener
  # LoadBalancerListener:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - TargetGroupArn: !Ref LoadBalancerListenerTargetGroupECS
  #         Type: 'forward'
  #     LoadBalancerArn: !Ref LoadBalancer
  #     Port: 80
  #     Protocol: HTTP
  #   DependsOn:
  #     - LoadBalancer

  # ECS Cluster
  ECSFargateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref EcsClusterName
      Tags: 
        - Key: project
          Value: 'gosling-dmc'

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSFargateCluster
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 50
      DesiredCount: 2
      EnableECSManagedTags: true
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !Ref TaskName
          ContainerPort: 8000
          TargetGroupArn: !Ref LoadBalancerListenerTargetGroupECS
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt ECSSecurityGroup.GroupId
          Subnets: !Ref PublicSubnetIds
          # Subnets: !Join [ ",", [!Ref PrivateSubnetIds, !Ref PublicSubnetIds] ]
      Tags: 
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSService'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'gosling-dmc'
      TaskDefinition: !Ref ECSServiceTaskDefinition
    DependsOn:
      - LoadBalancerListenerTargetGroupECS
      - LoadBalancer
  #     - LoadBalancerListener

  # ECS Task Definition
  ECSServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Ref TaskName
          Image: !Ref ImageURI 
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          EnvironmentFiles: 
            - Type: s3
              Value: !Ref TaskEnvFile
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub
                - "/ecs/${Task}-task-definition"
                - Task: !Ref TaskName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command: 
              - "CMD-SHELL"
              - "curl -f http://127.0.0.1:8000/health || exit 1"

            Interval: 30
            Timeout: 5
            Retries: 3
      Cpu: '1024'
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      Family: !Sub
        - "${Task}-task-definition"
        - Task: !Ref TaskName
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Tags:
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSTaskDef'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'gosling-dmc'
        - Key: component
          Value: 'gosling-dmc-api'
      TaskRoleArn: !Ref TaskContainerRole
    DependsOn:
      - TaskContainerRole

  TaskContainerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: gosling-dmc-api-container
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket                  
                Resource: [
                  !Ref TaskEnvFile,
                ]
              - Sid: ECS
                Effect: Allow
                Action:
                  - ecs:DescribeTasks
                Resource: "*"
              - Sid: RdsAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DbInfo
              - Sid: ECR
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: "*"
              - Sid: GetIP
                Effect: Allow
                Action:
                  - ec2:DescribeNetworkInterfaces
                  - ecs:DescribeTaskDefinition
                Resource: '*'
              - Sid: Logging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: ["arn:aws:logs:*:*:*"]
      Tags:
        - Key: Name
          Value: !Sub
            - '${StackName}:TaskContainerRole'
            - StackName: !Ref AWS::StackName
        - Key: project
          Value: 'gosling-dmc'
        - Key: component
          Value: 'gosling-dmc-api'

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ecs-service-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Sid: RdsAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DbInfo
        - PolicyName: cloudwatch-logs-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"
        - PolicyName: s3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucket                  
                Resource: [
                  !Ref TaskEnvFile,
                ]
      Tags:
        - Key: Name
          Value: !Sub
            - '${StackName}:ECSExecutionRole'
            - StackName: !Ref AWS::StackName

  # # Create the VPC Link configured with the private subnets. Security groups are kept empty here, but can be configured as required.
  # VpcLink:
  #   Type: 'AWS::ApiGatewayV2::VpcLink'
  #   Properties:
  #     Name: APIGWVpcLinkToPrivateHTTPEndpoint-2
  #     SubnetIds: !Ref PrivateSubnetIds
  #     SecurityGroupIds: []
  #   DependsOn:
  #     - TaskContainerRole
  #     - ECSServiceTaskDefinition

  # # Create the API Gateway HTTP endpoint
  # APIGWHTTPEndpoint:
  #   Type: 'AWS::ApiGatewayV2::Api'
  #   Properties:
  #     Name: serverlessland-pvt-endpoint
  #     ProtocolType: HTTP
  # # Create the API Gateway HTTP_PROXY integration between the created API and the private load balancer via the VPC Link.
  # # Ensure that the 'DependsOn' attribute has the VPC Link dependency.
  # # This is to ensure that the VPC Link is created successfully before the integration and the API GW routes are created.
  # APIGWHTTPEndpointIntegration:
  #   Type: 'AWS::ApiGatewayV2::Integration'
  #   Properties:
  #     ApiId: !Ref APIGWHTTPEndpoint
  #     IntegrationType: HTTP_PROXY
  #     ConnectionId: !Ref VpcLink
  #     ConnectionType: VPC_LINK
  #     IntegrationMethod: ANY
  #     IntegrationUri: !Ref LoadBalancerListener
  #     PayloadFormatVersion: '1.0'
  #   DependsOn:
  #   - VpcLink
  #   - APIGWHTTPEndpoint
  #   - LoadBalancerListener
  # # API GW route with ANY method
  # APIGWRoute:
  #   Type: 'AWS::ApiGatewayV2::Route'
  #   Properties:
  #     ApiId: !Ref APIGWHTTPEndpoint
  #     RouteKey: 'ANY /{proxy+}'
  #     Target: !Join 
  #       - /
  #       - - integrations
  #         - !Ref APIGWHTTPEndpointIntegration
  #   DependsOn:
  #   - APIGWHTTPEndpointIntegration
  # # Set a default stage
  # APIStageDefault:
  #   Type: 'AWS::ApiGatewayV2::Stage'
  #   Properties:
  #     ApiId: !Ref APIGWHTTPEndpoint
  #     StageName: $default
  #     AutoDeploy: true
  #   DependsOn:
  #     - APIGWHTTPEndpoint

Outputs:
  # Generated API GW endpoint URL that can be used to access the application running on a private ECS Fargate cluster.
  # APIGWEndpoint:
  #   Description: API Gateway Endpoint
  #   Value: !GetAtt APIGWHTTPEndpoint.ApiEndpoint

  ECSCluster: 
    Description: A reference to the ECS cluster
    Value: !Ref ECSFargateCluster

  ECSClusterTaskDef: 
    Description: The ECS cluster task definition
    Value: !Ref ECSServiceTaskDefinition

  # ECSClusterService: 
  #   Description: The ECS cluster service definition
  #   Value: !Ref ECSService

  ECSExecutionRole: 
    Description: The ECS execution role
    Value: !Ref ECSExecutionRole

  # LoadBalancerDNSName:
  #   Description: "DNS name of the load balancer"
  #   Value: !GetAtt LoadBalancer.DNSName

  # ExternalUrl:
  #   Description: The url of the external load balancer
  #   Value: !Sub http://${LoadBalancer.DNSName}
