upstream web_app {
    server backend:8000;
}

server {
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;

    server_name vis-api.link;

    ssl_certificate /etc/nginx/ssl/live/vis-api.link/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/vis-api.link/privkey.pem;
    
    location / {
    	proxy_pass http://vis-api.link;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name vis-api.link;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://vis-api.link$request_uri;
    }
}