import { useMemo } from "react";
import createFetchClient from "openapi-fetch";
import { type Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";

import type { paths } from "../types/schema.d.ts"; // generated by openapi-typescript
import { useAuthToken } from "./auth.ts";

const API_URL: string = import.meta.env.VITE_API_URL;

const fetchClient = createFetchClient<paths>({
  baseUrl: API_URL,
});

type QueryOptions = Partial<{ params: { query: Record<string, unknown> } }>;

function useAuthMiddleware() {
  const getToken = useAuthToken();

  const authMiddleware: Middleware = useMemo(
    () => ({
      async onRequest({ request }) {
        const token = await getToken();
        request.headers.set("Authorization", `Bearer ${token}`);
        return request;
      },
    }),
    [getToken]
  );

  return authMiddleware;
}

function useClient() {
  const authMiddleware = useAuthMiddleware();
  fetchClient.use(authMiddleware);
  return createClient(fetchClient);
}

export type { QueryOptions };
export default useClient;
