import { useAuth0 } from "@auth0/auth0-react";
import type { Query } from "@tanstack/react-query";
import createFetchClient, { type Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import { useMemo } from "react";
import type { paths } from "../types/schema.d.ts"; // generated by openapi-typescript
import { useAuthToken } from "./auth.ts";

const API_URL: string = import.meta.env.VITE_API_URL;

const fetchClient = createFetchClient<paths>({
  baseUrl: API_URL,
});

type QueryOptions = Partial<{ params: { query: Record<string, unknown> } }>;

function useAuthMiddleware() {
  const getToken = useAuthToken();

  const authMiddleware: Middleware = useMemo(
    () => ({
      async onRequest({ request }) {
        const token = await getToken();
        request.headers.set("Authorization", `Bearer ${token}`);
        // Identifies this client to the backend's API usage middleware so
        // requests can be split out from the Python client on the dashboard.
        request.headers.set("X-CVH-Client", "web");
        return request;
      },
    }),
    [getToken],
  );

  return authMiddleware;
}

function useClient() {
  const authMiddleware = useAuthMiddleware();
  const { isAuthenticated } = useAuth0();
  if (isAuthenticated) {
    fetchClient.use(authMiddleware);
  }
  return createClient(fetchClient);
}

function buildInvalidateGetQuery(paths: string[]) {
  return (q: Query<unknown, Error, unknown, readonly unknown[]>) => {
    const queryKey = q?.queryKey;

    if (
      queryKey[0] === "get" &&
      paths.some(
        (path) =>
          typeof queryKey[1] === "string" && queryKey[1]?.startsWith(path),
      )
    ) {
      return true;
    }
    return false;
  };
}

export type { QueryOptions };
export { buildInvalidateGetQuery };
export default useClient;
