/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns profile information for the authenticated user.
         */
        get: operations["api_routers_users_get_user_info"];
        /**
         * Update current user
         * @description Updates profile fields (first name, last name) for the authenticated user.
         */
        put: operations["api_routers_users_update_user_info"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workspace members
         * @description Returns all members of a workspace with their permissions and profile info. Requires read access.
         */
        get: operations["api_routers_members_get_workspace_members"];
        /**
         * Update a workspace member
         * @description Updates a member's permissions on a workspace. Requires admin access. Cannot modify your own permissions.
         */
        put: operations["api_routers_members_update_workspace_member"];
        /**
         * Add a workspace member
         * @description Adds a user to a workspace with read permissions. Requires admin access to the workspace.
         */
        post: operations["api_routers_members_add_workspace_member"];
        /**
         * Remove a workspace member
         * @description Removes a user from a workspace. Requires admin access. Cannot remove yourself.
         */
        delete: operations["api_routers_members_delete_workspace_member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user workspaces
         * @description Returns all private workspaces the authenticated user has read access to, ordered by last modified. Paginated.
         */
        get: operations["api_routers_workspaces_get_workspaces"];
        put?: never;
        /**
         * Create a workspace
         * @description Creates a new workspace. The authenticated user becomes the admin and an initial visualization is created.
         */
        post: operations["api_routers_workspaces_create_workspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a workspace
         * @description Returns a single workspace by UUID. Accessible if the workspace is public or the user has read access.
         */
        get: operations["api_routers_workspaces_get_workspace"];
        /**
         * Update a workspace
         * @description Partially updates a workspace's name, description, or visibility. Requires admin access.
         */
        put: operations["api_routers_workspaces_update_workspace"];
        post?: never;
        /**
         * Delete a workspace
         * @description Permanently deletes a workspace and all associated data. Requires admin access.
         */
        delete: operations["api_routers_workspaces_delete_workspace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List public workspaces
         * @description Returns all public workspaces, ordered by last modified. Paginated.
         */
        get: operations["api_routers_workspaces_get_public_workspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user datasets
         * @description Returns all datasets owned directly by the authenticated user (not via workspace). Paginated.
         */
        get: operations["api_routers_datasets_get_user_datasets"];
        put?: never;
        /**
         * Create a dataset
         * @description Creates a new dataset. If workspace_uuid is provided, requires write access to that workspace. Otherwise associates with the user directly.
         */
        post: operations["api_routers_datasets_create_dataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add example datasets
         * @description Populates a workspace with pre-configured example datasets and optionally visualizations. Requires write access.
         */
        post: operations["api_routers_datasets_create_example_datasets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a dataset
         * @description Returns a single dataset by UUID, including its tags. Requires read access to the parent workspace.
         */
        get: operations["api_routers_datasets_get_dataset"];
        /**
         * Update a dataset
         * @description Partially updates a dataset's metadata. Requires write access to the parent workspace.
         */
        put: operations["api_routers_datasets_update_dataset"];
        post?: never;
        /**
         * Delete a dataset
         * @description Permanently deletes a dataset. Requires write access to the parent workspace.
         */
        delete: operations["api_routers_datasets_delete_dataset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_uuid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Tag a dataset
         * @description Replaces all tags on a dataset. Creates any tags that don't already exist in the workspace. Requires write access.
         */
        put: operations["api_routers_datasets_tag_dataset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workspace datasets
         * @description Returns datasets in a workspace, with optional filtering by tags, assembly, file type, or name. Paginated.
         */
        get: operations["api_routers_datasets_get_workspace_datasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}/datasets/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dataset field values
         * @description Returns distinct values for a given field (assembly or file_type) across all datasets in a workspace. Useful for populating filter dropdowns.
         */
        get: operations["api_routers_datasets_get_workspace_datasets_field_values"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}/datasets/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dataset tags
         * @description Returns all distinct tags used by datasets in a workspace.
         */
        get: operations["api_routers_datasets_get_workspace_datasets_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_uuid}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start cfdb processing for a dataset
         * @description Dispatches the cfdb processing workflow for a cfdb-sourced dataset. The frontend polls cfdb's /jobs/{id} directly after dispatch. Requires write access to the parent workspace.
         */
        post: operations["api_routers_datasets_process_dataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_uuid}/processing-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Report cfdb processing outcome
         * @description Persists the terminal outcome of a cfdb processing job after the frontend has polled cfdb's /jobs/{id} directly. Only the STARTED state may transition into PROCESSED or FAILED via this endpoint. Requires write access to the parent workspace.
         */
        put: operations["api_routers_datasets_update_processing_status"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/visualizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published visualizations
         * @description Returns all published visualizations, with optional filtering by tags or UUIDs. Paginated. No authentication required.
         */
        get: operations["api_routers_visualizations_get_published_visualizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}/visualizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workspace visualizations
         * @description Returns visualizations in a workspace, with optional filtering by tags, name, or UUIDs. Requires read access.
         */
        get: operations["api_routers_visualizations_get_workspace_visualizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_uuid}/visualizations/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get visualization tags
         * @description Returns all distinct tags used by visualizations in a workspace.
         */
        get: operations["api_routers_visualizations_get_workspace_visualizations_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations/{visualization_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a visualization
         * @description Returns a single visualization by UUID, including its full configuration. Requires read access to the parent workspace.
         */
        get: operations["api_routers_visualizations_get_visualization"];
        /**
         * Update a visualization
         * @description Partially updates a visualization's metadata or configuration. Sets published_timestamp when publishing. Requires write access.
         */
        put: operations["api_routers_visualizations_update_visualization"];
        post?: never;
        /**
         * Delete a visualization
         * @description Permanently deletes a visualization. Requires write access to the parent workspace.
         */
        delete: operations["api_routers_visualizations_delete_visualization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/visualizations/{visualization_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a public visualization
         * @description Returns a single published visualization by UUID. No authentication required.
         */
        get: operations["api_routers_visualizations_get_public_visualization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations/{visualization_uuid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Tag a visualization
         * @description Replaces all tags on a visualization. Creates any tags that don't already exist in the workspace. Requires write access.
         */
        put: operations["api_routers_visualizations_tag_visualization"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a visualization
         * @description Creates a new visualization in a workspace. Requires write access to the workspace.
         */
        post: operations["api_routers_visualizations_create_visualization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search tags
         * @description Returns all tags, optionally filtered by a substring match on the combined 'key:tag' value. Paginated.
         */
        get: operations["api_routers_tags_get_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** UserOut */
        UserOut: {
            /** Username */
            username: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** SuccessOut */
        SuccessOut: {
            /** Success */
            success: boolean;
        };
        /** UserIn */
        UserIn: {
            /** First Name */
            first_name?: string;
            /** Last Name */
            last_name?: string;
        };
        /** WorkspaceMemberIn */
        WorkspaceMemberIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** WorkspaceMemberUpdate */
        WorkspaceMemberUpdate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Permissions
             * @default 1
             */
            permissions: number;
        };
        /** WorkspaceMemberOut */
        WorkspaceMemberOut: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /**
             * Permissions
             * @default 1
             */
            permissions: number;
        };
        /** WorkspaceIn */
        WorkspaceIn: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Private */
            private: boolean;
        };
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PagedWorkspaceOutWithMembersCount */
        PagedWorkspaceOutWithMembersCount: {
            /** Items */
            items: components["schemas"]["WorkspaceOutWithMembersCount"][];
            /** Count */
            count: number;
        };
        /** WorkspaceOutWithMembersCount */
        WorkspaceOutWithMembersCount: {
            /** Datasets Count */
            datasets_count: number;
            /** Visualizations Count */
            visualizations_count: number;
            /** Permissions */
            permissions?: number | null;
            /**
             * Private
             * @default true
             */
            private: boolean;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: date-time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: date-time
             */
            last_viewed_timestamp: string;
            /** Workspace Members Count */
            workspace_members_count: number;
        };
        /** WorkspaceOut */
        WorkspaceOut: {
            /** Datasets Count */
            datasets_count: number;
            /** Visualizations Count */
            visualizations_count: number;
            /** Permissions */
            permissions?: number | null;
            /**
             * Private
             * @default true
             */
            private: boolean;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: date-time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: date-time
             */
            last_viewed_timestamp: string;
        };
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Name */
            name?: string;
            /** Description */
            description?: string | null;
            /** Private */
            private?: boolean;
        };
        /** PagedWorkspaceOut */
        PagedWorkspaceOut: {
            /** Items */
            items: components["schemas"]["WorkspaceOut"][];
            /** Count */
            count: number;
        };
        /** DatasetIn */
        DatasetIn: {
            /** Workspace Uuid */
            workspace_uuid?: string | null;
            /**
             * Tool
             * @default gosling
             */
            tool?: "gosling" | "vitessce";
            /** Dataset */
            dataset: components["schemas"]["GoslingDatasetSimple"] | components["schemas"]["GoslingDesignerBam"] | components["schemas"]["GoslingDesignerMultiVec"] | components["schemas"]["GoslingDesignerIndex"] | components["schemas"]["GoslingDesignerBEDB"] | components["schemas"]["GoslingDesignerCSV"] | components["schemas"]["VitessceDataset"];
        };
        /** VitessceDataset */
        VitessceDataset: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "ome-tiff" | "ome-zarr" | "anndata.zarr" | "spatialdata.zarr";
        };
        /** GoslingDatasetSimple */
        GoslingDatasetSimple: {
            /**
             * Assembly
             * @enum {string}
             */
            assembly: "hg38" | "hg19" | "hg18" | "hg17" | "hg16" | "mm10" | "mm9" | "unknown";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "bigwig" | "cooler" | "vector";
        };
        /** GoslingDesignerBEDB */
        GoslingDesignerBEDB: {
            /** Data Column */
            data_column?: [
                string,
                "nominal" | "quantitative" | "chromosome" | "genomic" | "key"
            ][] | null;
            /**
             * Assembly
             * @enum {string}
             */
            assembly: "hg38" | "hg19" | "hg18" | "hg17" | "hg16" | "mm10" | "mm9" | "unknown";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "beddb";
        };
        /** GoslingDesignerBam */
        GoslingDesignerBam: {
            /** Cfdb Dcc */
            cfdb_dcc?: string | null;
            /** Cfdb Id */
            cfdb_id?: string | null;
            /**
             * Assembly
             * @enum {string}
             */
            assembly: "hg38" | "hg19" | "hg18" | "hg17" | "hg16" | "mm10" | "mm9" | "unknown";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "bam";
            /** Index Url */
            index_url?: string | null;
        };
        /** GoslingDesignerCSV */
        GoslingDesignerCSV: {
            /**
             * Assembly
             * @enum {string}
             */
            assembly: "hg38" | "hg19" | "hg18" | "hg17" | "hg16" | "mm10" | "mm9" | "unknown";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "csv";
            /** Separator */
            separator: string;
            /** Headers */
            headers: boolean;
            /** Data Column */
            data_column: [
                string,
                "nominal" | "quantitative" | "chromosome" | "genomic" | "key"
            ][];
        };
        /** GoslingDesignerIndex */
        GoslingDesignerIndex: {
            /** Cfdb Dcc */
            cfdb_dcc?: string | null;
            /** Cfdb Id */
            cfdb_id?: string | null;
            /** Data Column */
            data_column?: [
                string,
                "nominal" | "quantitative" | "chromosome" | "genomic" | "key"
            ][] | null;
            /**
             * Assembly
             * @enum {string}
             */
            assembly: "hg38" | "hg19" | "hg18" | "hg17" | "hg16" | "mm10" | "mm9" | "unknown";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "bed" | "gff" | "vcf";
            /** Index Url */
            index_url?: string | null;
        };
        /** GoslingDesignerMultiVec */
        GoslingDesignerMultiVec: {
            /**
             * Assembly
             * @enum {string}
             */
            assembly: "hg38" | "hg19" | "hg18" | "hg17" | "hg16" | "mm10" | "mm9" | "unknown";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** Data Type */
            data_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            file_type: "multivec";
            /** Row Names */
            row_names: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Source Url */
            source_url: string;
            /** File Type */
            file_type: string;
            /**
             * Tool
             * @default gosling
             */
            tool: "gosling" | "vitessce";
            /** Data Type */
            data_type: string;
            /** Assembly */
            assembly?: string | null;
            /** Data Column */
            data_column?: Record<string, never> | null;
            /** Row Names */
            row_names?: unknown[] | null;
            /**
             * Headers
             * @default false
             */
            headers: boolean;
            /** Index Url */
            index_url?: string | null;
            /** Separator */
            separator?: string | null;
            /** Cfdb Dcc */
            cfdb_dcc?: string | null;
            /** Cfdb Id */
            cfdb_id?: string | null;
            /**
             * Processing Status
             * @default not_needed
             */
            processing_status: string;
            /** Processing Job Id */
            processing_job_id?: string | null;
            /** Processing Started At */
            processing_started_at?: string | null;
            /** Processing Completed At */
            processing_completed_at?: string | null;
            /** Processing Error */
            processing_error?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: date-time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: date-time
             */
            last_viewed_timestamp: string;
        };
        /** PagedDatasetOut */
        PagedDatasetOut: {
            /** Items */
            items: components["schemas"]["DatasetOut"][];
            /** Count */
            count: number;
        };
        /** ExampleDatasetIn */
        ExampleDatasetIn: {
            /**
             * Workspace Uuid
             * Format: uuid4
             */
            workspace_uuid: string;
            /** Include Visualizations */
            include_visualizations: boolean;
            /**
             * Example Id
             * @enum {integer}
             */
            example_id: 1 | 2;
        };
        /** DatasetUpdate */
        DatasetUpdate: {
            /** Name */
            name?: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url?: string;
            /** File Type */
            file_type?: string;
            /** Data Type */
            data_type?: string;
            /** Assembly */
            assembly?: string | null;
            /** Data Column */
            data_column?: Record<string, never> | null;
            /** Row Names */
            row_names?: unknown[] | null;
            /** Headers */
            headers?: boolean;
            /** Index Url */
            index_url?: string | null;
            /** Separator */
            separator?: string | null;
        };
        /** DatasetWithTagsOut */
        DatasetWithTagsOut: {
            /** Source Url */
            source_url: string;
            /** File Type */
            file_type: string;
            /** Data Type */
            data_type: string;
            /** Assembly */
            assembly?: string | null;
            /** Data Column */
            data_column?: Record<string, never> | null;
            /** Row Names */
            row_names?: unknown[] | null;
            /**
             * Headers
             * @default false
             */
            headers: boolean;
            /** Index Url */
            index_url?: string | null;
            /** Separator */
            separator?: string | null;
            /** Cfdb Dcc */
            cfdb_dcc?: string | null;
            /** Cfdb Id */
            cfdb_id?: string | null;
            /**
             * Processing Status
             * @default not_needed
             */
            processing_status: string;
            /** Processing Job Id */
            processing_job_id?: string | null;
            /** Processing Started At */
            processing_started_at?: string | null;
            /** Processing Completed At */
            processing_completed_at?: string | null;
            /** Processing Error */
            processing_error?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: date-time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: date-time
             */
            last_viewed_timestamp: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
        };
        /** TagOut */
        TagOut: {
            /** Tag */
            tag: string;
            /** Key */
            key?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
        };
        /** TagIn */
        TagIn: {
            /** Tag */
            tag: string;
            /** Key */
            key: string;
        };
        /** TagsIn */
        TagsIn: {
            /** Tags */
            tags: components["schemas"]["TagIn"][];
        };
        /** DatasetQuerySchema */
        DatasetQuerySchema: {
            /** Tags */
            tags?: string[];
            /** Assembly */
            assembly?: string[];
            /** File Type */
            file_type?: string[];
            /** Name */
            name?: string;
        };
        /** PagedDatasetWithTagsOut */
        PagedDatasetWithTagsOut: {
            /** Items */
            items: components["schemas"]["DatasetWithTagsOut"][];
            /** Count */
            count: number;
        };
        /**
         * ProcessingOut
         * @description Snapshot of a dataset's processing state. Returned by the dispatch
         *     and status-update endpoints so the frontend can update its view
         *     without a separate read.
         */
        ProcessingOut: {
            /** Processing Status */
            processing_status: string;
            /** Processing Job Id */
            processing_job_id?: string | null;
            /** Processing Started At */
            processing_started_at?: string | null;
            /** Processing Completed At */
            processing_completed_at?: string | null;
            /** Processing Error */
            processing_error?: string | null;
        };
        /**
         * ProcessingStatusUpdate
         * @description Client-reported terminal state for a processing job. The frontend
         *     polls cfdb's `/jobs/{id}` directly and PUTs the result here so that
         *     CVH persists the outcome across browser sessions. Only terminal
         *     statuses are accepted; transient `started` is set by the dispatch
         *     endpoint and shouldn't be reported back.
         */
        ProcessingStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "processed" | "failed";
            /** Error */
            error?: string | null;
        };
        /** VisualizationQuerySchema */
        VisualizationQuerySchema: {
            /** Tags */
            tags?: string[];
            /** Name */
            name?: string;
            /** Uuids */
            uuids?: string[];
        };
        /** PagedVisualizationSummaryOut */
        PagedVisualizationSummaryOut: {
            /** Items */
            items: components["schemas"]["VisualizationSummaryOut"][];
            /** Count */
            count: number;
        };
        /** VisualizationSummaryOut */
        VisualizationSummaryOut: {
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Author */
            author?: string | null;
            /**
             * Tool
             * @default gosling
             */
            tool: string;
            /**
             * Published
             * @default false
             */
            published: boolean;
            /**
             * N Tracks
             * @default 0
             */
            n_tracks: number | null;
            /**
             * N Datasets
             * @default 0
             */
            n_datasets: number | null;
            /** Published Timestamp */
            published_timestamp?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: date-time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: date-time
             */
            last_viewed_timestamp: string;
        };
        /** VisualizationOut */
        VisualizationOut: {
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Conf */
            conf?: Record<string, never> | null;
            /** Author */
            author?: string | null;
            /**
             * Tool
             * @default gosling
             */
            tool: string;
            /**
             * Published
             * @default false
             */
            published: boolean;
            /**
             * N Tracks
             * @default 0
             */
            n_tracks: number | null;
            /**
             * N Datasets
             * @default 0
             */
            n_datasets: number | null;
            /** Published Timestamp */
            published_timestamp?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: date-time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: date-time
             */
            last_viewed_timestamp: string;
        };
        /** VisualizationUpdate */
        VisualizationUpdate: {
            /** Name */
            name?: string;
            /** Description */
            description?: string | null;
            /** Author */
            author?: string | null;
            /** Tool */
            tool?: string;
            /** Conf */
            conf?: Record<string, never> | null;
            /** Published */
            published?: boolean;
            /** N Tracks */
            n_tracks?: number | null;
            /** N Datasets */
            n_datasets?: number | null;
        };
        /** VisualizationIn */
        VisualizationIn: {
            /**
             * Workspace Uuid
             * Format: uuid4
             */
            workspace_uuid: string;
            /** Description */
            description?: string | null;
            /** Author */
            author?: string | null;
            /** Name */
            name: string;
            /**
             * Tool
             * @default gosling
             */
            tool: string;
        };
        /** PagedTagOut */
        PagedTagOut: {
            /** Items */
            items: components["schemas"]["TagOut"][];
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_routers_users_get_user_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_routers_users_update_user_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_members_get_workspace_members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberOut"][];
                };
            };
        };
    };
    api_routers_members_update_workspace_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_members_add_workspace_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_members_delete_workspace_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_workspaces_get_workspaces: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedWorkspaceOutWithMembersCount"];
                };
            };
        };
    };
    api_routers_workspaces_create_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceIn"];
                };
            };
        };
    };
    api_routers_workspaces_get_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceOut"];
                };
            };
        };
    };
    api_routers_workspaces_update_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_workspaces_delete_workspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_workspaces_get_public_workspaces: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedWorkspaceOut"];
                };
            };
        };
    };
    api_routers_datasets_get_user_datasets: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDatasetOut"];
                };
            };
        };
    };
    api_routers_datasets_create_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetIn"];
                };
            };
        };
    };
    api_routers_datasets_create_example_datasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExampleDatasetIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_datasets_get_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetWithTagsOut"];
                };
            };
        };
    };
    api_routers_datasets_update_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_datasets_delete_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_datasets_tag_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_datasets_get_workspace_datasets: {
        parameters: {
            query?: {
                tags?: string[];
                assembly?: string[];
                file_type?: string[];
                name?: string;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDatasetWithTagsOut"];
                };
            };
        };
    };
    api_routers_datasets_get_workspace_datasets_field_values: {
        parameters: {
            query: {
                field: "assembly" | "file_type";
            };
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    api_routers_datasets_get_workspace_datasets_tags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    api_routers_datasets_process_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingOut"];
                };
            };
        };
    };
    api_routers_datasets_update_processing_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessingStatusUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingOut"];
                };
            };
        };
    };
    api_routers_visualizations_get_published_visualizations: {
        parameters: {
            query?: {
                tags?: string[];
                name?: string;
                uuids?: string[];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedVisualizationSummaryOut"];
                };
            };
        };
    };
    api_routers_visualizations_get_workspace_visualizations: {
        parameters: {
            query?: {
                tags?: string[];
                name?: string;
                uuids?: string[];
            };
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationSummaryOut"][];
                };
            };
        };
    };
    api_routers_visualizations_get_workspace_visualizations_tags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    api_routers_visualizations_get_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visualization_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationOut"];
                };
            };
        };
    };
    api_routers_visualizations_update_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visualization_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizationUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_visualizations_delete_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visualization_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_visualizations_get_public_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visualization_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationOut"];
                };
            };
        };
    };
    api_routers_visualizations_tag_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visualization_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessOut"];
                };
            };
        };
    };
    api_routers_visualizations_create_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizationIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationSummaryOut"];
                };
            };
        };
    };
    api_routers_tags_get_tags: {
        parameters: {
            query?: {
                sub_str?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTagOut"];
                };
            };
        };
    };
}
