/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projects */
        get: operations["api_api_get_projects"];
        put?: never;
        /** Create Project */
        post: operations["api_api_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["api_api_get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Datasets */
        get: operations["api_api_get_user_datasets"];
        put?: never;
        /** Create Dataset */
        post: operations["api_api_create_dataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{project_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Datasets */
        get: operations["api_api_get_project_datasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Visualizations */
        get: operations["api_api_get_project_visualizations"];
        put?: never;
        /** Create Visualization */
        post: operations["api_api_create_visualization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualizations/{visualization_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visualization */
        get: operations["api_api_get_visualization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ProjectOut */
        ProjectOut: {
            /**
             * Private
             * @default true
             */
            private: boolean;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: time
             */
            last_viewed_timestamp: string;
        };
        /** ProjectIn */
        ProjectIn: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Private */
            private: boolean;
        };
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PagedProjectOut */
        PagedProjectOut: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /** Count */
            count: number;
        };
        /** DatasetIn */
        DatasetIn: {
            /** Project Uuid */
            project_uuid?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Source Url */
            source_url: string;
            /** File Type */
            file_type: string;
            /** Data Type */
            data_type: string;
        };
        /** DatasetOut */
        DatasetOut: {
            /** Source Url */
            source_url: string;
            /** File Type */
            file_type: string;
            /** Data Type */
            data_type: string;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: time
             */
            last_viewed_timestamp: string;
        };
        /** PagedDatasetOut */
        PagedDatasetOut: {
            /** Items */
            items: components["schemas"]["DatasetOut"][];
            /** Count */
            count: number;
        };
        /** VisualizationNoConfOut */
        VisualizationNoConfOut: {
            /** Tool */
            tool: string;
            /** Tool Version */
            tool_version?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: time
             */
            last_viewed_timestamp: string;
        };
        /** VisualizationIn */
        VisualizationIn: {
            /**
             * Project Uuid
             * Format: uuid4
             */
            project_uuid: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Conf */
            conf: Record<string, never>;
            /** Tool */
            tool: string;
            /** Tool Version */
            tool_version?: string | null;
        };
        /** VisualizationOut */
        VisualizationOut: {
            /** Conf */
            conf: Record<string, never>;
            /** Tool */
            tool: string;
            /** Tool Version */
            tool_version?: string | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created Timestamp
             * Format: time
             */
            created_timestamp: string;
            /**
             * Modified Timestamp
             * Format: time
             */
            modified_timestamp: string;
            /**
             * Last Viewed Timestamp
             * Format: time
             */
            last_viewed_timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_api_get_projects: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedProjectOut"];
                };
            };
        };
    };
    api_api_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    api_api_get_user_datasets: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDatasetOut"];
                };
            };
        };
    };
    api_api_create_dataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetIn"];
                };
            };
        };
    };
    api_api_get_project_datasets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    api_api_get_project_visualizations: {
        parameters: {
            query: {
                project_uuid: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationNoConfOut"][];
                };
            };
        };
    };
    api_api_create_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizationIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationIn"];
                };
            };
        };
    };
    api_api_get_visualization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visualization_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualizationOut"];
                };
            };
        };
    };
}
