# Generated by Django 5.1.5 on 2025-02-11 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(max_length=300, null=True)),
                ('created_timestamp', models.TimeField(auto_now_add=True)),
                ('modified_timestamp', models.TimeField(auto_now=True)),
                ('last_viewed_timestamp', models.TimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(max_length=300, null=True)),
                ('created_timestamp', models.TimeField(auto_now_add=True)),
                ('modified_timestamp', models.TimeField(auto_now=True)),
                ('last_viewed_timestamp', models.TimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=True)),
                ('group_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('user_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(max_length=300, null=True)),
                ('created_timestamp', models.TimeField(auto_now_add=True)),
                ('modified_timestamp', models.TimeField(auto_now=True)),
                ('last_viewed_timestamp', models.TimeField(auto_now_add=True)),
                ('source_url', models.URLField(max_length=100)),
                ('file_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('user_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualizationConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(max_length=300, null=True)),
                ('created_timestamp', models.TimeField(auto_now_add=True)),
                ('modified_timestamp', models.TimeField(auto_now=True)),
                ('last_viewed_timestamp', models.TimeField(auto_now_add=True)),
                ('conf', models.JSONField()),
                ('tool', models.CharField(max_length=50)),
                ('tool_version', models.CharField(blank=True, max_length=50)),
                ('project_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
