# Generated by Django 5.1.5 on 2025-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_project_tags_tag_key_visualizationconf_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationconf',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
