# Generated by Django 5.1.5 on 2025-03-24 15:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_visualizationconf_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoslingBAMSourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('index_url', models.URLField(max_length=100)),
                ('max_insert_size', models.IntegerField(default=5000)),
                ('load_mates', models.BooleanField(default=False)),
                ('junction_min_coverage', models.IntegerField(default=1)),
                ('extract_junction', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingBEDSourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('index_url', models.URLField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
                ('custom_fields', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingBigWigSourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('value', models.CharField(default='value', max_length=100)),
                ('start', models.CharField(default='start', max_length=100)),
                ('end', models.CharField(default='end', max_length=100)),
                ('column', models.CharField(default='position', max_length=100)),
                ('bin_size', models.IntegerField(default=1)),
                ('aggregation', models.CharField(default='mean', max_length=100, validators=[api.models.validate_bigwig_aggregation])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingGenomicCSVSourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('separator', models.CharField(max_length=5)),
                ('sample_length', models.IntegerField(default=1000)),
                ('long_to_wide_id', models.CharField(max_length=100)),
                ('header_names', models.JSONField()),
                ('genomic_fields_to_convert', models.JSONField()),
                ('genomic_fields', models.JSONField()),
                ('chromosome_prefix', models.CharField(max_length=50)),
                ('chromosome_field', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingGGF3SourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('index_url', models.URLField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
                ('attributes_to_fields', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingJSONSourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('sample_length', models.IntegerField(default=1000)),
                ('genomic_fields_to_convert', models.JSONField()),
                ('genomic_fields', models.JSONField()),
                ('chromosome_field', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingVCFDataSourceConfig',
            fields=[
                ('dataset', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.dataset')),
                ('index_url', models.URLField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
