# Generated by Django 5.1.5 on 2025-09-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_visualizationconf_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizationconf',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='visualizationconf',
            name='tool_version',
        ),
        migrations.AlterField(
            model_name='visualizationconf',
            name='conf',
            field=models.JSONField(null=True),
        ),
    ]
