# Generated by Django 5.1.5 on 2025-03-22 01:13

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_visualizationconf_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoslingBAMDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('index_url', models.URLField(max_length=100)),
                ('max_insert_size', models.IntegerField(default=5000)),
                ('load_mates', models.BooleanField(default=False)),
                ('junction_min_coverage', models.IntegerField(default=1)),
                ('extract_junction', models.BooleanField(default=False)),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingBEDDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('index_url', models.URLField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
                ('custom_fields', models.JSONField()),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingBigWigDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.CharField(default='value', max_length=100)),
                ('start', models.CharField(default='start', max_length=100)),
                ('end', models.CharField(default='end', max_length=100)),
                ('column', models.CharField(default='position', max_length=100)),
                ('binSize', models.IntegerField(default=1)),
                ('aggregation', models.CharField(default='mean', max_length=100, validators=[api.models.validate_bigwig_aggregation])),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingCSVDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('separator', models.CharField(max_length=5)),
                ('sample_length', models.IntegerField(default=1000)),
                ('longToWideId', models.CharField(max_length=100)),
                ('headerNames', models.JSONField()),
                ('genomicFieldsToConvert', models.JSONField()),
                ('genomicFields', models.JSONField()),
                ('chromosomePrefix', models.CharField(max_length=50)),
                ('chromosomeField', models.CharField(max_length=50)),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingGGF3Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('index_url', models.URLField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
                ('attributes_to_fields', models.JSONField()),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingJSONDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
                ('genomic_fields_to_convert', models.JSONField()),
                ('genomic_fields', models.JSONField()),
                ('chromosome_field', models.CharField(max_length=50)),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoslingVCFDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('index_url', models.URLField(max_length=100)),
                ('sample_length', models.IntegerField(default=1000)),
                ('dataset_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
