# Generated by Django 5.1.5 on 2025-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_tag_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationconf',
            name='published_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
