# Generated by Django 5.1.5 on 2025-10-30 15:59

from django.db import migrations, models

def update_owner_permissions(apps, schema_editor):
    MyModel = apps.get_model('api', 'ProjectMember')
    for obj in MyModel.objects.filter(permissions=4):
        obj.permissions = 3
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_visualizationconf_published_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='permissions',
            field=models.IntegerField(choices=[(1, 'read'), (2, 'write'), (3, 'admin')], default=1),
        ),
        migrations.RunPython(update_owner_permissions)
    ]
