# Generated by Django 5.1.5 on 2025-11-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_projectmember_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationconf',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
