# Generated by Django 5.2.11 on 2026-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_dataset_index_url_alter_dataset_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizationconf',
            name='tool',
            field=models.CharField(choices=[('gosling', 'Gosling'), ('vitessce', 'Vitessce')], default='gosling', max_length=10),
        ),
    ]
