# Generated by Django 5.2.11 on 2026-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_visualizationconf_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Project Group', 'verbose_name_plural': 'Project Groups'},
        ),
    ]
