# Generated by Django 5.2.11 on 2026-05-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualizationconf',
            options={'verbose_name': 'Visualization', 'verbose_name_plural': 'Visualizations'},
        ),
    ]
