/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizationsVisualizationIdRouteImport } from './routes/visualizations.$visualizationId'
import { Route as TutorialsChar123SlugChar125RouteImport } from './routes/tutorials.{-$slug}'
import { Route as ProjectChar123ProjectIdChar125RouteImport } from './routes/project.{-$projectId}'
import { Route as ProjectVitessceChar123ProjectIdChar125RouteImport } from './routes/project.vitessce.{-$projectId}'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsVisualizationIdRoute =
  VisualizationsVisualizationIdRouteImport.update({
    id: '/visualizations/$visualizationId',
    path: '/visualizations/$visualizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TutorialsChar123SlugChar125Route =
  TutorialsChar123SlugChar125RouteImport.update({
    id: '/tutorials/{-$slug}',
    path: '/tutorials/{-$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectChar123ProjectIdChar125Route =
  ProjectChar123ProjectIdChar125RouteImport.update({
    id: '/project/{-$projectId}',
    path: '/project/{-$projectId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectVitessceChar123ProjectIdChar125Route =
  ProjectVitessceChar123ProjectIdChar125RouteImport.update({
    id: '/project/vitessce/{-$projectId}',
    path: '/project/vitessce/{-$projectId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/profile': typeof ProfileRoute
  '/project/{-$projectId}': typeof ProjectChar123ProjectIdChar125Route
  '/tutorials/{-$slug}': typeof TutorialsChar123SlugChar125Route
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceChar123ProjectIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/profile': typeof ProfileRoute
  '/project/{-$projectId}': typeof ProjectChar123ProjectIdChar125Route
  '/tutorials/{-$slug}': typeof TutorialsChar123SlugChar125Route
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceChar123ProjectIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/profile': typeof ProfileRoute
  '/project/{-$projectId}': typeof ProjectChar123ProjectIdChar125Route
  '/tutorials/{-$slug}': typeof TutorialsChar123SlugChar125Route
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceChar123ProjectIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/profile'
    | '/project/{-$projectId}'
    | '/tutorials/{-$slug}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/profile'
    | '/project/{-$projectId}'
    | '/tutorials/{-$slug}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/profile'
    | '/project/{-$projectId}'
    | '/tutorials/{-$slug}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ProfileRoute: typeof ProfileRoute
  ProjectChar123ProjectIdChar125Route: typeof ProjectChar123ProjectIdChar125Route
  TutorialsChar123SlugChar125Route: typeof TutorialsChar123SlugChar125Route
  VisualizationsVisualizationIdRoute: typeof VisualizationsVisualizationIdRoute
  ProjectVitessceChar123ProjectIdChar125Route: typeof ProjectVitessceChar123ProjectIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations/$visualizationId': {
      id: '/visualizations/$visualizationId'
      path: '/visualizations/$visualizationId'
      fullPath: '/visualizations/$visualizationId'
      preLoaderRoute: typeof VisualizationsVisualizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/{-$slug}': {
      id: '/tutorials/{-$slug}'
      path: '/tutorials/{-$slug}'
      fullPath: '/tutorials/{-$slug}'
      preLoaderRoute: typeof TutorialsChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/{-$projectId}': {
      id: '/project/{-$projectId}'
      path: '/project/{-$projectId}'
      fullPath: '/project/{-$projectId}'
      preLoaderRoute: typeof ProjectChar123ProjectIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/vitessce/{-$projectId}': {
      id: '/project/vitessce/{-$projectId}'
      path: '/project/vitessce/{-$projectId}'
      fullPath: '/project/vitessce/{-$projectId}'
      preLoaderRoute: typeof ProjectVitessceChar123ProjectIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ProfileRoute: ProfileRoute,
  ProjectChar123ProjectIdChar125Route: ProjectChar123ProjectIdChar125Route,
  TutorialsChar123SlugChar125Route: TutorialsChar123SlugChar125Route,
  VisualizationsVisualizationIdRoute: VisualizationsVisualizationIdRoute,
  ProjectVitessceChar123ProjectIdChar125Route:
    ProjectVitessceChar123ProjectIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
