/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as IndexImport } from './routes/index'
import { Route as VisualizationsVisualizationIdImport } from './routes/visualizations.$visualizationId'
import { Route as TutorialsSlugImport } from './routes/tutorials.{-$slug}'
import { Route as ProjectProjectIdImport } from './routes/project.{-$projectId}'
import { Route as ProjectVitessceProjectIdImport } from './routes/project.vitessce.{-$projectId}'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VisualizationsVisualizationIdRoute =
  VisualizationsVisualizationIdImport.update({
    id: '/visualizations/$visualizationId',
    path: '/visualizations/$visualizationId',
    getParentRoute: () => rootRoute,
  } as any)

const TutorialsSlugRoute = TutorialsSlugImport.update({
  id: '/tutorials/{-$slug}',
  path: '/tutorials/{-$slug}',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectIdRoute = ProjectProjectIdImport.update({
  id: '/project/{-$projectId}',
  path: '/project/{-$projectId}',
  getParentRoute: () => rootRoute,
} as any)

const ProjectVitessceProjectIdRoute = ProjectVitessceProjectIdImport.update({
  id: '/project/vitessce/{-$projectId}',
  path: '/project/vitessce/{-$projectId}',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/project/{-$projectId}': {
      id: '/project/{-$projectId}'
      path: '/project/{-$projectId}'
      fullPath: '/project/{-$projectId}'
      preLoaderRoute: typeof ProjectProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/tutorials/{-$slug}': {
      id: '/tutorials/{-$slug}'
      path: '/tutorials/{-$slug}'
      fullPath: '/tutorials/{-$slug}'
      preLoaderRoute: typeof TutorialsSlugImport
      parentRoute: typeof rootRoute
    }
    '/visualizations/$visualizationId': {
      id: '/visualizations/$visualizationId'
      path: '/visualizations/$visualizationId'
      fullPath: '/visualizations/$visualizationId'
      preLoaderRoute: typeof VisualizationsVisualizationIdImport
      parentRoute: typeof rootRoute
    }
    '/project/vitessce/{-$projectId}': {
      id: '/project/vitessce/{-$projectId}'
      path: '/project/vitessce/{-$projectId}'
      fullPath: '/project/vitessce/{-$projectId}'
      preLoaderRoute: typeof ProjectVitessceProjectIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/project/{-$projectId}': typeof ProjectProjectIdRoute
  '/tutorials/{-$slug}': typeof TutorialsSlugRoute
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceProjectIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/project/{-$projectId}': typeof ProjectProjectIdRoute
  '/tutorials/{-$slug}': typeof TutorialsSlugRoute
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/project/{-$projectId}': typeof ProjectProjectIdRoute
  '/tutorials/{-$slug}': typeof TutorialsSlugRoute
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/project/{-$projectId}'
    | '/tutorials/{-$slug}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/project/{-$projectId}'
    | '/tutorials/{-$slug}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/project/{-$projectId}'
    | '/tutorials/{-$slug}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  TutorialsSlugRoute: typeof TutorialsSlugRoute
  VisualizationsVisualizationIdRoute: typeof VisualizationsVisualizationIdRoute
  ProjectVitessceProjectIdRoute: typeof ProjectVitessceProjectIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  TutorialsSlugRoute: TutorialsSlugRoute,
  VisualizationsVisualizationIdRoute: VisualizationsVisualizationIdRoute,
  ProjectVitessceProjectIdRoute: ProjectVitessceProjectIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/project/{-$projectId}",
        "/tutorials/{-$slug}",
        "/visualizations/$visualizationId",
        "/project/vitessce/{-$projectId}"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/project/{-$projectId}": {
      "filePath": "project.{-$projectId}.tsx"
    },
    "/tutorials/{-$slug}": {
      "filePath": "tutorials.{-$slug}.tsx"
    },
    "/visualizations/$visualizationId": {
      "filePath": "visualizations.$visualizationId.tsx"
    },
    "/project/vitessce/{-$projectId}": {
      "filePath": "project.vitessce.{-$projectId}.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
