/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizationsVisualizationIdRouteImport } from './routes/visualizations.$visualizationId'
import { Route as ProjectChar123ProjectIdChar125RouteImport } from './routes/project.{-$projectId}'
import { Route as ProjectVitessceChar123ProjectIdChar125RouteImport } from './routes/project.vitessce.{-$projectId}'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationsVisualizationIdRoute =
  VisualizationsVisualizationIdRouteImport.update({
    id: '/visualizations/$visualizationId',
    path: '/visualizations/$visualizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectChar123ProjectIdChar125Route =
  ProjectChar123ProjectIdChar125RouteImport.update({
    id: '/project/{-$projectId}',
    path: '/project/{-$projectId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectVitessceChar123ProjectIdChar125Route =
  ProjectVitessceChar123ProjectIdChar125RouteImport.update({
    id: '/project/vitessce/{-$projectId}',
    path: '/project/vitessce/{-$projectId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-sources': typeof DataSourcesRoute
  '/datasets': typeof DatasetsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/project/{-$projectId}': typeof ProjectChar123ProjectIdChar125Route
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceChar123ProjectIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-sources': typeof DataSourcesRoute
  '/datasets': typeof DatasetsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/project/{-$projectId}': typeof ProjectChar123ProjectIdChar125Route
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceChar123ProjectIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-sources': typeof DataSourcesRoute
  '/datasets': typeof DatasetsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/project/{-$projectId}': typeof ProjectChar123ProjectIdChar125Route
  '/visualizations/$visualizationId': typeof VisualizationsVisualizationIdRoute
  '/project/vitessce/{-$projectId}': typeof ProjectVitessceChar123ProjectIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-sources'
    | '/datasets'
    | '/profile'
    | '/projects'
    | '/project/{-$projectId}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-sources'
    | '/datasets'
    | '/profile'
    | '/projects'
    | '/project/{-$projectId}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  id:
    | '__root__'
    | '/'
    | '/data-sources'
    | '/datasets'
    | '/profile'
    | '/projects'
    | '/project/{-$projectId}'
    | '/visualizations/$visualizationId'
    | '/project/vitessce/{-$projectId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DatasetsRoute: typeof DatasetsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectChar123ProjectIdChar125Route: typeof ProjectChar123ProjectIdChar125Route
  VisualizationsVisualizationIdRoute: typeof VisualizationsVisualizationIdRoute
  ProjectVitessceChar123ProjectIdChar125Route: typeof ProjectVitessceChar123ProjectIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizations/$visualizationId': {
      id: '/visualizations/$visualizationId'
      path: '/visualizations/$visualizationId'
      fullPath: '/visualizations/$visualizationId'
      preLoaderRoute: typeof VisualizationsVisualizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/{-$projectId}': {
      id: '/project/{-$projectId}'
      path: '/project/{-$projectId}'
      fullPath: '/project/{-$projectId}'
      preLoaderRoute: typeof ProjectChar123ProjectIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/vitessce/{-$projectId}': {
      id: '/project/vitessce/{-$projectId}'
      path: '/project/vitessce/{-$projectId}'
      fullPath: '/project/vitessce/{-$projectId}'
      preLoaderRoute: typeof ProjectVitessceChar123ProjectIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataSourcesRoute: DataSourcesRoute,
  DatasetsRoute: DatasetsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectChar123ProjectIdChar125Route: ProjectChar123ProjectIdChar125Route,
  VisualizationsVisualizationIdRoute: VisualizationsVisualizationIdRoute,
  ProjectVitessceChar123ProjectIdChar125Route:
    ProjectVitessceChar123ProjectIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
