"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import boto3
import requests
from botocore.exceptions import ClientError
from environs import env

env.read_env()
# Override in .env for local development
DEBUG = env.bool("DEBUG", default=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

IS_DEVELOPMENT_SERVER = DEBUG

ALLOWED_HOSTS = []
METADATA_URI = env.str("ECS_CONTAINER_METADATA_URI_V4")


def get_ecs_allowed_hosts(uri):
    region_name = "us-east-2"

    session = boto3.session.Session()
    ecs_client = session.client(service_name="ecs", region_name=region_name)
    ec2_client = session.client(service_name="ec2", region_name=region_name)

    container_metadata = requests.get(uri).json()
    container_ip = container_metadata["Networks"][0]["IPv4Addresses"][0]

    task_metadata = requests.get(f"{uri}/task").json()

    cluster = task_metadata["Cluster"]
    task_arn = task_metadata["TaskARN"]
    try:
        tasks = ecs_client.describe_tasks(cluster=cluster, tasks=[task_arn])
    except ClientError as e:
        raise e

    task = tasks["tasks"][0]
    attachments = task.get("attachments", [])
    eni_id = None

    for attachment in attachments:
        if attachment.get("type") == "ElasticNetworkInterface":
            details = attachment.get("details", [])
            for detail in details:
                if detail.get("name") == "networkInterfaceId":
                    eni_id = detail.get("value")
    if eni_id:
        try:
            network_interfaces = ec2_client.describe_network_interfaces(
                NetworkInterfaceIds=[eni_id],
            )
        except ClientError as e:
            raise e

        return [
            container_ip,
            network_interfaces["NetworkInterfaces"][0]["Association"]["PublicIp"],
        ]
    return [container_ip]


if METADATA_URI:
    ecs_hosts = get_ecs_allowed_hosts(METADATA_URI) or []
    ALLOWED_HOSTS.extend(ecs_hosts)


ENV_ALLOWED_HOSTS = env.str("ALLOWED_HOSTS").split(",")

if ENV_ALLOWED_HOSTS:
    ALLOWED_HOSTS.extend(ENV_ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "mozilla_django_oidc",
    "api",
    "health_check",
]

MIDDLEWARE = [
    "core.middleware.HealthCheckMiddleware",
    # ApiUsageMiddleware wraps everything below so it can record the final
    # response status/duration for every request (including 4xx/5xx).
    "core.middleware.ApiUsageMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise must sit directly after SecurityMiddleware so it can
    # serve collected static files (admin CSS/JS) from the container,
    # without needing a CDN or a sidecar nginx.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

# The same image runs in two ECS services. SERVICE_VARIANT picks which URL
# surface this process exposes — "api" mounts the public REST API, "admin"
# mounts only the Django admin. Defaulting to "api" preserves existing
# local + production behavior.
SERVICE_VARIANT = env.str("SERVICE_VARIANT", default="api")
if SERVICE_VARIANT not in {"api", "admin"}:
    raise ValueError(
        f"SERVICE_VARIANT must be 'api' or 'admin', got {SERVICE_VARIANT!r}"
    )

ROOT_URLCONF = (
    "core.urls_admin" if SERVICE_VARIANT == "admin" else "core.urls"
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# Credentials (DB_USER, DB_PASSWORD) and SECRET_KEY are pulled from a
# consolidated AWS Secrets Manager entry in production. Injection is
# handled by ECS itself via the task definition's `Secrets:` field
# (see cloudformation/back-end.yml), so the app reads them from env
# uniformly in dev (.env) and prod.

DB_USER = env.str("DB_USER")
DB_PASSWORD = env.str("DB_PASSWORD")

DB_OPTIONS = {}

if not IS_DEVELOPMENT_SERVER or METADATA_URI:
    DB_OPTIONS["sslmode"] = "require"

DATABASES = {
    "default": {
        "ENGINE": env.str("DB_ENGINE"),
        "NAME": env.str("DB_NAME"),
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": env.str("DB_HOST"),
        "PORT": env.int("DB_PORT"),
        "OPTIONS": DB_OPTIONS,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
# `collectstatic` runs during the Docker build; the resulting files are
# served by WhiteNoise at runtime. Locally this dir may not exist until
# you've run `manage.py collectstatic` once.
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        # Hashed filenames + gzip/brotli so WhiteNoise can serve with
        # long-lived cache headers safely.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Base URL for cfdb, the data-processing service. Used to derive
# `Dataset.source_url` for datasets backed by cfdb. Strip any trailing slash.
# Defaults to the dev environment; override in prod via the env file.
CFDB_BASE_URL = env.str(
    "CFDB_BASE_URL", default="https://dev.cfdb.vis-api.link"
).rstrip("/")

CORS_ALLOWED_ORIGINS = env.str("ALLOWED_ORIGINS").split(",")

# Allow the custom client-identification header the frontend and the Python
# client send for API usage tracking.
from corsheaders.defaults import default_headers  # noqa: E402

CORS_ALLOW_HEADERS = (*default_headers, "x-cvh-client")

# Structured logging for the ApiUsageMiddleware. The middleware emits a single
# JSON object per request line; we leave the formatter as a passthrough so
# CloudWatch Logs receives the JSON exactly as written. Logs Insights and the
# Embedded Metric Format parser both ingest the JSON directly.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "passthrough": {"format": "%(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "passthrough",
        },
    },
    "loggers": {
        "api_usage": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# We sit behind an ALB that terminates TLS and forwards plain HTTP to
# the container. Without this, Django thinks every request is HTTP, so
# `request.is_secure()` is False and `request.build_absolute_uri(...)`
# produces `http://...` — which breaks OIDC (Auth0 rejects the
# `redirect_uri` because it's registered as `https://`) and any other
# scheme-aware URL building. Trusting `X-Forwarded-Proto` is safe here
# because the only thing that can reach the Fargate task is the ALB
# (enforced by the ECS security group).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Auth0-backed OIDC for the Django admin SERVICE_VARIANT. The client_id
# and client_secret are sensitive; in production they come from the
# AppSecretsArn entry via ECS `Secrets:` injection (see
# cloudformation/back-end.yml). Domain / claim names are operational
# config, not secrets. The api SERVICE_VARIANT also imports these (no
# harm — the URLs aren't mounted there) so both processes share the
# same settings module.

AUTH0_DOMAIN = env.str("AUTH0_DOMAIN", default="")
AUTH0_ADMIN_CLIENT_ID = env.str("AUTH0_ADMIN_CLIENT_ID", default="")
AUTH0_ADMIN_CLIENT_SECRET = env.str("AUTH0_ADMIN_CLIENT_SECRET", default="")

# mozilla-django-oidc settings — Auth0 endpoints follow a fixed pattern.
# `AUTH0_DOMAIN` is shared with `api/auth.py`, which expects the full URL
# form `https://<tenant>/` (used as a JWT issuer). Strip protocol and
# trailing slash here so the OIDC endpoint URLs come out clean.
_auth0_host = (
    AUTH0_DOMAIN.removeprefix("https://").removeprefix("http://").rstrip("/")
)
OIDC_RP_CLIENT_ID = AUTH0_ADMIN_CLIENT_ID
OIDC_RP_CLIENT_SECRET = AUTH0_ADMIN_CLIENT_SECRET
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"https://{_auth0_host}/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"https://{_auth0_host}/oauth/token"
OIDC_OP_USER_ENDPOINT = f"https://{_auth0_host}/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"https://{_auth0_host}/.well-known/jwks.json"

# Read by core.oidc_backend.Auth0AdminOIDCBackend.
OIDC_ADMIN_ROLE_CLAIM = env.str(
    "OIDC_ADMIN_ROLE_CLAIM", default="https://cvh/roles"
)
OIDC_ADMIN_ROLE_NAME = env.str("OIDC_ADMIN_ROLE_NAME", default="cvh_admin")

if SERVICE_VARIANT == "admin":
    AUTHENTICATION_BACKENDS = ("core.oidc_backend.Auth0AdminOIDCBackend",)
    LOGIN_URL = "/oidc/authenticate/"
    LOGIN_REDIRECT_URL = "/admin/"
    LOGOUT_REDIRECT_URL = "/admin/"
