"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import boto3
import requests
from botocore.exceptions import ClientError
from environs import env

env.read_env()
# Override in .env for local development
DEBUG = env.bool("DEBUG", default=False)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

IS_DEVELOPMENT_SERVER = DEBUG

ALLOWED_HOSTS = []
METADATA_URI = env.str("ECS_CONTAINER_METADATA_URI_V4")


def get_ecs_allowed_hosts(uri):
    region_name = "us-east-2"

    session = boto3.session.Session()
    ecs_client = session.client(service_name="ecs", region_name=region_name)
    ec2_client = session.client(service_name="ec2", region_name=region_name)

    container_metadata = requests.get(uri).json()
    container_ip = container_metadata["Networks"][0]["IPv4Addresses"][0]

    task_metadata = requests.get(f"{uri}/task").json()

    cluster = task_metadata["Cluster"]
    task_arn = task_metadata["TaskARN"]
    try:
        tasks = ecs_client.describe_tasks(cluster=cluster, tasks=[task_arn])
    except ClientError as e:
        raise e

    task = tasks["tasks"][0]
    attachments = task.get("attachments", [])
    eni_id = None

    for attachment in attachments:
        if attachment.get("type") == "ElasticNetworkInterface":
            details = attachment.get("details", [])
            for detail in details:
                if detail.get("name") == "networkInterfaceId":
                    eni_id = detail.get("value")
    if eni_id:
        try:
            network_interfaces = ec2_client.describe_network_interfaces(
                NetworkInterfaceIds=[eni_id],
            )
        except ClientError as e:
            raise e

        return [
            container_ip,
            network_interfaces["NetworkInterfaces"][0]["Association"]["PublicIp"],
        ]
    return [container_ip]


if METADATA_URI:
    ecs_hosts = get_ecs_allowed_hosts(METADATA_URI) or []
    ALLOWED_HOSTS.extend(ecs_hosts)


ENV_ALLOWED_HOSTS = env.str("ALLOWED_HOSTS").split(",")

if ENV_ALLOWED_HOSTS:
    ALLOWED_HOSTS.extend(ENV_ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "mozilla_django_oidc",
    "api",
    "health_check",
]

MIDDLEWARE = [
    "core.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

# The same image runs in two ECS services. SERVICE_VARIANT picks which URL
# surface this process exposes — "api" mounts the public REST API, "admin"
# mounts only the Django admin. Defaulting to "api" preserves existing
# local + production behavior.
SERVICE_VARIANT = env.str("SERVICE_VARIANT", default="api")
if SERVICE_VARIANT not in {"api", "admin"}:
    raise ValueError(
        f"SERVICE_VARIANT must be 'api' or 'admin', got {SERVICE_VARIANT!r}"
    )

ROOT_URLCONF = (
    "core.urls_admin" if SERVICE_VARIANT == "admin" else "core.urls"
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# Credentials (DB_USER, DB_PASSWORD) and SECRET_KEY are pulled from a
# consolidated AWS Secrets Manager entry in production. Injection is
# handled by ECS itself via the task definition's `Secrets:` field
# (see cloudformation/back-end.yml), so the app reads them from env
# uniformly in dev (.env) and prod.

DB_USER = env.str("DB_USER")
DB_PASSWORD = env.str("DB_PASSWORD")

DB_OPTIONS = {}

if not IS_DEVELOPMENT_SERVER or METADATA_URI:
    DB_OPTIONS["sslmode"] = "require"

DATABASES = {
    "default": {
        "ENGINE": env.str("DB_ENGINE"),
        "NAME": env.str("DB_NAME"),
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": env.str("DB_HOST"),
        "PORT": env.int("DB_PORT"),
        "OPTIONS": DB_OPTIONS,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = env.str("ALLOWED_ORIGINS").split(",")


# Auth0-backed OIDC for the Django admin SERVICE_VARIANT.
# Only the client_secret is sensitive — in production it's pulled from
# Secrets Manager (see get_admin_oidc_secret below); locally it lives in
# .env. Domain / client_id / claim names are operational config, not
# secrets. The api SERVICE_VARIANT also imports these (no harm — the URLs
# aren't mounted there) so both processes share the same settings module.

AUTH0_DOMAIN = env.str("AUTH0_DOMAIN", default="")
AUTH0_ADMIN_CLIENT_ID = env.str("AUTH0_ADMIN_CLIENT_ID", default="")
AUTH0_ADMIN_CLIENT_SECRET = env.str("AUTH0_ADMIN_CLIENT_SECRET", default="")


def get_admin_oidc_secret() -> dict[str, str]:
    secret_name = env.str("AUTH0_ADMIN_SECRET_NAME")
    region_name = "us-east-2"
    session = boto3.session.Session()
    client = session.client(service_name="secretsmanager", region_name=region_name)
    try:
        response = client.get_secret_value(SecretId=secret_name)
    except ClientError as e:
        raise e
    return json.loads(response["SecretString"])


if METADATA_URI and SERVICE_VARIANT == "admin":
    admin_oidc_secrets = get_admin_oidc_secret()
    AUTH0_ADMIN_CLIENT_ID = admin_oidc_secrets["client_id"]
    AUTH0_ADMIN_CLIENT_SECRET = admin_oidc_secrets["client_secret"]

# mozilla-django-oidc settings — Auth0 endpoints follow a fixed pattern.
OIDC_RP_CLIENT_ID = AUTH0_ADMIN_CLIENT_ID
OIDC_RP_CLIENT_SECRET = AUTH0_ADMIN_CLIENT_SECRET
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"https://{AUTH0_DOMAIN}/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"https://{AUTH0_DOMAIN}/oauth/token"
OIDC_OP_USER_ENDPOINT = f"https://{AUTH0_DOMAIN}/userinfo"
OIDC_OP_JWKS_ENDPOINT = f"https://{AUTH0_DOMAIN}/.well-known/jwks.json"

# Read by core.oidc_backend.Auth0AdminOIDCBackend.
OIDC_ADMIN_ROLE_CLAIM = env.str(
    "OIDC_ADMIN_ROLE_CLAIM", default="https://cvh/roles"
)
OIDC_ADMIN_ROLE_NAME = env.str("OIDC_ADMIN_ROLE_NAME", default="cvh_admin")

if SERVICE_VARIANT == "admin":
    AUTHENTICATION_BACKENDS = ("core.oidc_backend.Auth0AdminOIDCBackend",)
    LOGIN_URL = "/oidc/authenticate/"
    LOGIN_REDIRECT_URL = "/admin/"
    LOGOUT_REDIRECT_URL = "/admin/"
